### ISSUE TITLE
Store build logs or diffoscope html output

### ISSUE THREAD

**Issue by jelly** [kpcyrd/rebuilderd#7]
Currently it's only possible to investigate why a build was unreproducible by rebuilding it locally and running for example diffoscope. It would be nice to be able to view the build log, results or diffoscope html output via an API call.

**Comment by aparcar** [comment]
Any news on this end? Would be really nice to have linkable diffoscope outputs!

**Comment by kpcyrd** [comment]
workers can be configured to report a diffoscope diff, but I forgot to actually persist that diff on the daemon. I've also started working on log capturing, I was a bit hesitant adding this because we've had issues capturing logs of nspawn with journald and because async-await was still very new in rust back then, but after I attempted this it seems to work correctly.

I'm trying to get both of this into the next release.
